title: sensehat-scratch2-mp3-player
hero_image: images/banner.png
description: sensehat-scratch2-mp3-player description
version: 4
listed: false
copyedit: false
last_tested: "2019-09-11"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
